module.exports = [
  {
    epId: 1,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep1',
    epNum: 1,
    filmId: 1,
  },
  {
    epId: 2,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep2',
    epNum: 2,
    filmId: 1,
  },
  {
    epId: 3,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep3',
    epNum: 3,
    filmId: 1,
  },
  {
    epId: 4,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep4',
    epNum: 4,
    filmId: 1,
  },
  {
    epId: 5,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep5',
    epNum: 5,
    filmId: 1,
  },
  {
    epId: 6,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep6',
    epNum: 6,
    filmId: 1,
  },
  {
    epId: 7,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep7',
    epNum: 7,
    filmId: 1,
  },
  {
    epId: 8,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep8',
    epNum: 8,
    filmId: 1,
  },
  {
    epId: 9,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep9',
    epNum: 9,
    filmId: 1,
  },
  {
    epId: 10,
    name: 'The begin of the war',
    description: 'The war has begun',
    uri: 'GOTss1ep10',
    epNum: 10,
    filmId: 1,
  },
];
